/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Clever.Client.SwaggerDateConverter;

namespace Clever.Model
{
    /// <summary>
    /// District
    /// </summary>
    [DataContract]
    public partial class District :  IEquatable<District>, IValidatableObject
    {
        /// <summary>
        /// Defines State
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StateEnum
        {
            
            /// <summary>
            /// Enum Running for value: running
            /// </summary>
            [EnumMember(Value = "running")]
            Running = 1,
            
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending = 2,
            
            /// <summary>
            /// Enum Error for value: error
            /// </summary>
            [EnumMember(Value = "error")]
            Error = 3,
            
            /// <summary>
            /// Enum Paused for value: paused
            /// </summary>
            [EnumMember(Value = "paused")]
            Paused = 4,
            
            /// <summary>
            /// Enum Empty for value: 
            /// </summary>
            [EnumMember(Value = "")]
            Empty = 5,
            
            /// <summary>
            /// Enum Success for value: success
            /// </summary>
            [EnumMember(Value = "success")]
            Success = 6
        }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public StateEnum? State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="District" /> class.
        /// </summary>
        /// <param name="districtContact">districtContact.</param>
        /// <param name="error">error.</param>
        /// <param name="id">id.</param>
        /// <param name="lastSync">lastSync.</param>
        /// <param name="launchDate">launchDate.</param>
        /// <param name="loginMethods">loginMethods.</param>
        /// <param name="mdrNumber">mdrNumber.</param>
        /// <param name="name">name.</param>
        /// <param name="ncesId">ncesId.</param>
        /// <param name="pauseEnd">pauseEnd.</param>
        /// <param name="pauseStart">pauseStart.</param>
        /// <param name="portalUrl">portalUrl.</param>
        /// <param name="sisType">sisType.</param>
        /// <param name="state">state.</param>
        public District(DistrictContact districtContact = default(DistrictContact), string error = default(string), string id = default(string), string lastSync = default(string), DateTime? launchDate = default(DateTime?), List<string> loginMethods = default(List<string>), string mdrNumber = default(string), string name = default(string), string ncesId = default(string), string pauseEnd = default(string), string pauseStart = default(string), string portalUrl = default(string), string sisType = default(string), StateEnum? state = default(StateEnum?))
        {
            this.DistrictContact = districtContact;
            this.Error = error;
            this.Id = id;
            this.LastSync = lastSync;
            this.LaunchDate = launchDate;
            this.LoginMethods = loginMethods;
            this.MdrNumber = mdrNumber;
            this.Name = name;
            this.NcesId = ncesId;
            this.PauseEnd = pauseEnd;
            this.PauseStart = pauseStart;
            this.PortalUrl = portalUrl;
            this.SisType = sisType;
            this.State = state;
        }
        
        /// <summary>
        /// Gets or Sets DistrictContact
        /// </summary>
        [DataMember(Name="district_contact", EmitDefaultValue=false)]
        public DistrictContact DistrictContact { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name="error", EmitDefaultValue=false)]
        public string Error { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets LastSync
        /// </summary>
        [DataMember(Name="last_sync", EmitDefaultValue=false)]
        public string LastSync { get; set; }

        /// <summary>
        /// Gets or Sets LaunchDate
        /// </summary>
        [DataMember(Name="launch_date", EmitDefaultValue=false)]
        [JsonConverter(typeof(SwaggerDateConverter))]
        public DateTime? LaunchDate { get; set; }

        /// <summary>
        /// Gets or Sets LoginMethods
        /// </summary>
        [DataMember(Name="login_methods", EmitDefaultValue=false)]
        public List<string> LoginMethods { get; set; }

        /// <summary>
        /// Gets or Sets MdrNumber
        /// </summary>
        [DataMember(Name="mdr_number", EmitDefaultValue=false)]
        public string MdrNumber { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets NcesId
        /// </summary>
        [DataMember(Name="nces_id", EmitDefaultValue=false)]
        public string NcesId { get; set; }

        /// <summary>
        /// Gets or Sets PauseEnd
        /// </summary>
        [DataMember(Name="pause_end", EmitDefaultValue=false)]
        public string PauseEnd { get; set; }

        /// <summary>
        /// Gets or Sets PauseStart
        /// </summary>
        [DataMember(Name="pause_start", EmitDefaultValue=false)]
        public string PauseStart { get; set; }

        /// <summary>
        /// Gets or Sets PortalUrl
        /// </summary>
        [DataMember(Name="portal_url", EmitDefaultValue=false)]
        public string PortalUrl { get; set; }

        /// <summary>
        /// Gets or Sets SisType
        /// </summary>
        [DataMember(Name="sis_type", EmitDefaultValue=false)]
        public string SisType { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class District {\n");
            sb.Append("  DistrictContact: ").Append(DistrictContact).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LastSync: ").Append(LastSync).Append("\n");
            sb.Append("  LaunchDate: ").Append(LaunchDate).Append("\n");
            sb.Append("  LoginMethods: ").Append(LoginMethods).Append("\n");
            sb.Append("  MdrNumber: ").Append(MdrNumber).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NcesId: ").Append(NcesId).Append("\n");
            sb.Append("  PauseEnd: ").Append(PauseEnd).Append("\n");
            sb.Append("  PauseStart: ").Append(PauseStart).Append("\n");
            sb.Append("  PortalUrl: ").Append(PortalUrl).Append("\n");
            sb.Append("  SisType: ").Append(SisType).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as District);
        }

        /// <summary>
        /// Returns true if District instances are equal
        /// </summary>
        /// <param name="input">Instance of District to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(District input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DistrictContact == input.DistrictContact ||
                    (this.DistrictContact != null &&
                    this.DistrictContact.Equals(input.DistrictContact))
                ) && 
                (
                    this.Error == input.Error ||
                    (this.Error != null &&
                    this.Error.Equals(input.Error))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.LastSync == input.LastSync ||
                    (this.LastSync != null &&
                    this.LastSync.Equals(input.LastSync))
                ) && 
                (
                    this.LaunchDate == input.LaunchDate ||
                    (this.LaunchDate != null &&
                    this.LaunchDate.Equals(input.LaunchDate))
                ) && 
                (
                    this.LoginMethods == input.LoginMethods ||
                    this.LoginMethods != null &&
                    this.LoginMethods.SequenceEqual(input.LoginMethods)
                ) && 
                (
                    this.MdrNumber == input.MdrNumber ||
                    (this.MdrNumber != null &&
                    this.MdrNumber.Equals(input.MdrNumber))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.NcesId == input.NcesId ||
                    (this.NcesId != null &&
                    this.NcesId.Equals(input.NcesId))
                ) && 
                (
                    this.PauseEnd == input.PauseEnd ||
                    (this.PauseEnd != null &&
                    this.PauseEnd.Equals(input.PauseEnd))
                ) && 
                (
                    this.PauseStart == input.PauseStart ||
                    (this.PauseStart != null &&
                    this.PauseStart.Equals(input.PauseStart))
                ) && 
                (
                    this.PortalUrl == input.PortalUrl ||
                    (this.PortalUrl != null &&
                    this.PortalUrl.Equals(input.PortalUrl))
                ) && 
                (
                    this.SisType == input.SisType ||
                    (this.SisType != null &&
                    this.SisType.Equals(input.SisType))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DistrictContact != null)
                    hashCode = hashCode * 59 + this.DistrictContact.GetHashCode();
                if (this.Error != null)
                    hashCode = hashCode * 59 + this.Error.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.LastSync != null)
                    hashCode = hashCode * 59 + this.LastSync.GetHashCode();
                if (this.LaunchDate != null)
                    hashCode = hashCode * 59 + this.LaunchDate.GetHashCode();
                if (this.LoginMethods != null)
                    hashCode = hashCode * 59 + this.LoginMethods.GetHashCode();
                if (this.MdrNumber != null)
                    hashCode = hashCode * 59 + this.MdrNumber.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.NcesId != null)
                    hashCode = hashCode * 59 + this.NcesId.GetHashCode();
                if (this.PauseEnd != null)
                    hashCode = hashCode * 59 + this.PauseEnd.GetHashCode();
                if (this.PauseStart != null)
                    hashCode = hashCode * 59 + this.PauseStart.GetHashCode();
                if (this.PortalUrl != null)
                    hashCode = hashCode * 59 + this.PortalUrl.GetHashCode();
                if (this.SisType != null)
                    hashCode = hashCode * 59 + this.SisType.GetHashCode();
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
