/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Clever.Client.SwaggerDateConverter;

namespace Clever.Model
{
    /// <summary>
    /// Event
    /// </summary>
    [DataContract]
    [JsonConverter(typeof(JsonSubtypes), "type")]
    [JsonSubtypes.KnownSubType(typeof(DistrictsUpdated), "districts.updated")]
    [JsonSubtypes.KnownSubType(typeof(TermsCreated), "terms.created")]
    [JsonSubtypes.KnownSubType(typeof(DistrictsDeleted), "districts.deleted")]
    [JsonSubtypes.KnownSubType(typeof(TermsDeleted), "terms.deleted")]
    [JsonSubtypes.KnownSubType(typeof(TermsUpdated), "terms.updated")]
    [JsonSubtypes.KnownSubType(typeof(DistrictsCreated), "districts.created")]
    [JsonSubtypes.KnownSubType(typeof(ResourcesDeleted), "resources.deleted")]
    [JsonSubtypes.KnownSubType(typeof(UsersUpdated), "users.updated")]
    [JsonSubtypes.KnownSubType(typeof(SectionsCreated), "sections.created")]
    [JsonSubtypes.KnownSubType(typeof(UsersCreated), "users.created")]
    [JsonSubtypes.KnownSubType(typeof(CoursesCreated), "courses.created")]
    [JsonSubtypes.KnownSubType(typeof(SchoolsCreated), "schools.created")]
    [JsonSubtypes.KnownSubType(typeof(CoursesDeleted), "courses.deleted")]
    [JsonSubtypes.KnownSubType(typeof(CoursesUpdated), "courses.updated")]
    [JsonSubtypes.KnownSubType(typeof(SectionsDeleted), "sections.deleted")]
    [JsonSubtypes.KnownSubType(typeof(SectionsUpdated), "sections.updated")]
    [JsonSubtypes.KnownSubType(typeof(SchoolsDeleted), "schools.deleted")]
    [JsonSubtypes.KnownSubType(typeof(SchoolsUpdated), "schools.updated")]
    [JsonSubtypes.KnownSubType(typeof(UsersDeleted), "users.deleted")]
    [JsonSubtypes.KnownSubType(typeof(ResourcesUpdated), "resources.updated")]
    [JsonSubtypes.KnownSubType(typeof(ResourcesCreated), "resources.created")]
    public partial class Event :  IEquatable<Event>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Event" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Event() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Event" /> class.
        /// </summary>
        /// <param name="created">created.</param>
        /// <param name="id">id.</param>
        /// <param name="type">type (required).</param>
        public Event(string created = default(string), string id = default(string), string type = default(string))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for Event and cannot be null");
            }
            else
            {
                this.Type = type;
            }
            this.Created = created;
            this.Id = id;
        }
        
        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [DataMember(Name="created", EmitDefaultValue=false)]
        public string Created { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Event {\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Event);
        }

        /// <summary>
        /// Returns true if Event instances are equal
        /// </summary>
        /// <param name="input">Instance of Event to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Event input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Created == input.Created ||
                    (this.Created != null &&
                    this.Created.Equals(input.Created))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Created != null)
                    hashCode = hashCode * 59 + this.Created.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
