/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Clever.Api;
using Clever.Model;
using Clever.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Clever.Test
{
    /// <summary>
    ///  Class for testing ResourceObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResourceObjectTests
    {
        // TODO uncomment below to declare an instance variable for ResourceObject
        //private ResourceObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResourceObject
            //instance = new ResourceObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResourceObject
        /// </summary>
        [Test]
        public void ResourceObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResourceObject
            //Assert.IsInstanceOfType<ResourceObject> (instance, "variable 'instance' is a ResourceObject");
        }


        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

    }

}
