/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Clever.Api;
using Clever.Model;
using Clever.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Clever.Test
{
    /// <summary>
    ///  Class for testing Roles
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RolesTests
    {
        // TODO uncomment below to declare an instance variable for Roles
        //private Roles instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Roles
            //instance = new Roles();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Roles
        /// </summary>
        [Test]
        public void RolesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Roles
            //Assert.IsInstanceOfType<Roles> (instance, "variable 'instance' is a Roles");
        }


        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Test]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
        /// <summary>
        /// Test the property 'DistrictAdmin'
        /// </summary>
        [Test]
        public void DistrictAdminTest()
        {
            // TODO unit test for the property 'DistrictAdmin'
        }
        /// <summary>
        /// Test the property 'Staff'
        /// </summary>
        [Test]
        public void StaffTest()
        {
            // TODO unit test for the property 'Staff'
        }
        /// <summary>
        /// Test the property 'Student'
        /// </summary>
        [Test]
        public void StudentTest()
        {
            // TODO unit test for the property 'Student'
        }
        /// <summary>
        /// Test the property 'Teacher'
        /// </summary>
        [Test]
        public void TeacherTest()
        {
            // TODO unit test for the property 'Teacher'
        }

    }

}
