/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Clever.Api;
using Clever.Model;
using Clever.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Clever.Test
{
    /// <summary>
    ///  Class for testing SchoolEnrollment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SchoolEnrollmentTests
    {
        // TODO uncomment below to declare an instance variable for SchoolEnrollment
        //private SchoolEnrollment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SchoolEnrollment
            //instance = new SchoolEnrollment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SchoolEnrollment
        /// </summary>
        [Test]
        public void SchoolEnrollmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SchoolEnrollment
            //Assert.IsInstanceOfType<SchoolEnrollment> (instance, "variable 'instance' is a SchoolEnrollment");
        }


        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'School'
        /// </summary>
        [Test]
        public void SchoolTest()
        {
            // TODO unit test for the property 'School'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }

    }

}
