/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Clever.Api;
using Clever.Model;
using Clever.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Clever.Test
{
    /// <summary>
    ///  Class for testing Staff
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StaffTests
    {
        // TODO uncomment below to declare an instance variable for Staff
        //private Staff instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Staff
            //instance = new Staff();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Staff
        /// </summary>
        [Test]
        public void StaffInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Staff
            //Assert.IsInstanceOfType<Staff> (instance, "variable 'instance' is a Staff");
        }


        /// <summary>
        /// Test the property 'Credentials'
        /// </summary>
        [Test]
        public void CredentialsTest()
        {
            // TODO unit test for the property 'Credentials'
        }
        /// <summary>
        /// Test the property 'Department'
        /// </summary>
        [Test]
        public void DepartmentTest()
        {
            // TODO unit test for the property 'Department'
        }
        /// <summary>
        /// Test the property 'Ext'
        /// </summary>
        [Test]
        public void ExtTest()
        {
            // TODO unit test for the property 'Ext'
        }
        /// <summary>
        /// Test the property 'LegacyId'
        /// </summary>
        [Test]
        public void LegacyIdTest()
        {
            // TODO unit test for the property 'LegacyId'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Test]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }
        /// <summary>
        /// Test the property 'Schools'
        /// </summary>
        [Test]
        public void SchoolsTest()
        {
            // TODO unit test for the property 'Schools'
        }
        /// <summary>
        /// Test the property 'StaffId'
        /// </summary>
        [Test]
        public void StaffIdTest()
        {
            // TODO unit test for the property 'StaffId'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
