/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Clever.Api;
using Clever.Model;
using Clever.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Clever.Test
{
    /// <summary>
    ///  Class for testing StudentRelationship
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StudentRelationshipTests
    {
        // TODO uncomment below to declare an instance variable for StudentRelationship
        //private StudentRelationship instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StudentRelationship
            //instance = new StudentRelationship();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StudentRelationship
        /// </summary>
        [Test]
        public void StudentRelationshipInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StudentRelationship
            //Assert.IsInstanceOfType<StudentRelationship> (instance, "variable 'instance' is a StudentRelationship");
        }


        /// <summary>
        /// Test the property 'Relationship'
        /// </summary>
        [Test]
        public void RelationshipTest()
        {
            // TODO unit test for the property 'Relationship'
        }
        /// <summary>
        /// Test the property 'Student'
        /// </summary>
        [Test]
        public void StudentTest()
        {
            // TODO unit test for the property 'Student'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
